= You Owe Me - Logboek
:author: Jules Verstraeten
:toc: auto
:imagesdir: images

link:home.adoc[Home]

== TODO's

=== Versie Beta 1.0
Ik wil het meest simpelste versie van het programma, het enigste wat men moet kunnen doen is een contact toevoegen, een lening bij dat contact persoon open zetten, en een lening afbetaald zetten, als lening is afbetaald gaat de lening naar de historie

    * [*] Modellen maken
    * [] Functie's van modellen maken
    * [] Repositorie maken
    * [] UI maken

== Week 6
=== 05/02
Circa 2.5 uur

[.lead]
REST, database,..  welke?

    Ik heb vooral gezocht naar wat ik zou kunnen gebruiken voor mijn programma, welke rest api en database. Ik wou eerst voor C# ASP.NET gaan omdat ik dit zou moeten leren voor mijn opleiding en het zou goed staan voor mijn portofolio. Maar achteraf ben ik gaan twijfelen tussen ASP.NET of Django. Hier ga ik later op terug komen. Database zou PostgreSQL zijn op Supabase, dit is ook nog niet 100% zeker.

[.lead]
Logs bestand bijgehouden

    Ik heb heel veel aan het logbestand toegevoegd onderandere de classmodel en het design principes

=== 06/02
Circa 4-5 uur

    Ik heb vandaag heel veel aan de UI van de homepagina gewerkt, ik heb daarvoor vele testen gemaakt met modellen, lokale repositorie, lokale service en lokale viewmodels, alles werkt na verwacht. Alle modellen zijn tot nu toe goed qua design. Ik moet alleen nog wel de voorwaardes instellen van de modellen.