= You Owe Me - Logboek
:author: Jules Verstraeten
:toc: auto
:imagesdir: images

link:home.adoc[Home]

== TODO's

=== Versie Beta 1.0
Ik wil het meest simpelste versie van het programma, het enigste wat men moet kunnen doen is een contact toevoegen, een lening bij dat contact persoon open zetten, en een lening afbetaald zetten, als lening is afbetaald gaat de lening naar de historie

    * [*] Modellen maken
    * [] Functie's van modellen maken
    * [] Repositorie maken
    * [] UI maken

== Week 6
=== 05/02
Circa 2.5 uur

[.lead]
REST, database,..  welke?

    Ik heb vooral gezocht naar wat ik zou kunnen gebruiken voor mijn programma, welke rest api en database. Ik wou eerst voor C# ASP.NET gaan omdat ik dit zou moeten leren voor mijn opleiding en het zou goed staan voor mijn portofolio. Maar achteraf ben ik gaan twijfelen tussen ASP.NET of Django. Hier ga ik later op terug komen. Database zou PostgreSQL zijn op Supabase, dit is ook nog niet 100% zeker.

[.lead]
Logs bestand bijgehouden

    Ik heb heel veel aan het logbestand toegevoegd onderandere de classmodel en het design principes

=== 06/02
Circa 4-5 uur

[.lead]
UI, modellen en repositorie

    Ik heb vandaag heel veel aan de UI van de homepagina gewerkt, ik heb daarvoor vele testen gemaakt met modellen, lokale repositorie, lokale service en lokale viewmodels, alles werkt na verwacht. Alle modellen zijn tot nu toe goed qua design. Ik moet alleen nog wel de voorwaardes instellen van de modellen.

[.lead]
Veranderd (~)/toegevoegd (+)/verwijderd (-)

modellen:

* + User
* + Contact
* + Transaction
* + Payment

UI-views:

* ~ HomePage
* + TransactionPage
* + TransactionsPage
* + ContactPage
* + ContactsPage
* + AddTransactionPage
* + AddContactPage
* + EditTransactionPage

Verder:

* + Lokale repositorie
* + Lokale service
* + Lokale viewmodel
* + Invoices widget

=== 07/02
Circa 2.5 uur

[.lead]
State Management

    Ik ben nu achter gekomen dat State Management de beste optie is om data door te geven aan pagina's. Dit ga ik aanpakken aan mijn applicatie. State Management houd in dat er geen data hoeven doorgegeven te worden aan pagina's maar dat dit centraal worden opgeslagen in de viewmodel.

    Het aanpassen naar State Management was wel echt een hele gedoe, maar het werkt nu.

[.lead]
Veranderd (~)/toegevoegd (+)/verwijderd (-)

* - Lokale service (is niet nodig ivm viewModel)
* ~ Lokale viewModel (het veranderen naar State Manager methode)
* ~ Lokale repositorie (het aanpassen van totalAmount output(int -> string))
* ~ User model (totalAmount output)
* ~ Contact model (totalAmount output)
* ~ HomePage (het veranderen naar State Manager methode)
* ~ ContactPage (voorbereiden voor de ui)
* ~ InvoicesItemView (het veranderen naar State Manager methode)
* ~ Main (kleine aanpassingen en darkmode)
* ~ Theme (darkmode toepassing)
* ~ BottomNavBarWithoutActionButton (darkmode toepassing)

=== 08/02
Circa 5 uur

[.lead]
UI

    Hier heb ik vandaag het meest gewerkt. Maar ik kwam nogsteeds wel heel veel vragen op, vele dingen snap ik nog niet echt hoe ik het best kan aanpakken en toepassen. Hiervoor ga ik binnenkort even goed onderzoeken.

[.lead]
Veranderd (~)/toegevoegd (+)/verwijderd (-)

* Modellen:
** ~ Contact (Alle transactie geven methode)
** ~ Transaction (GetAmountString, GetTitle en GetStatus methodes toegepast)
* Views:
** ~ ContactPage (Heel contactpage ui gemaakt, alleen nog functioneel maken)
* Widgets:
** + InvoiceItemviewContactWidget (de transacties module voor contactpage)
** + ToggleButton (Toggle button voor contactpage (moet nog wel universeel gemaakt worden en echt beter geschreven worden))
* Theme (geselecteerde text en opgeselecteerde text een vaste kleur gegeven)
* Lokale repositorie (Fetchuser aangepast)
* Main (ik heb daar de repo vastgezet)
